config:
  aws:region: ap-southeast-1
  affinidi-verifier-portal:environment: loadtest
  affinidi-verifier-portal:website-name: affinidi-verifier-portal
  affinidi-verifier-portal:site-directory: ../build
  affinidi-verifier-portal:index-document: index.html
  affinidi-verifier-portal:create-acm-cert: false
  affinidi-verifier-portal:certificate-arn: arn:aws:acm:us-east-1:423240840743:certificate/ba87c461-e098-4819-8ea6-a0b4ba7eb9c8
